### ISSUE TITLE
Edition of abstracts

### ISSUE THREAD

**Issue by potockan** [eRum2016/Book-of-abstracts#1]
Is there a possibility to change an abstract to a presentation? I'd like to change mine (and I know some people would like to change theirs abstracts) and I wasn't able to do that at the end of August.
I was told to track the conference's GitHub group and to tag @Nowosad (as probably he is in charge of that). Please help.

**Comment by Nowosad** [comment]
Hi @potockan - yes, that's not a problem. The simplest way is to send me an email (nowosad.jakub@gmail.com) with your abstract.
