### ISSUE TITLE
Mapki na warsztaty

### ISSUE THREAD

**Issue by alicjaszabelska** [eRum2016/Book-of-abstracts#11]
@mkdyderski czy mogłbyś zrobić mapki z zaznaczeniem miejsc, gdzie będzie jaki warsztat. Tutaj masz rozpiskę, gdzie jaki warsztat się odbędzie.

[rozpiska_sal.xlsx](https://github.com/eRum2016/Book-of-abstracts/files/505692/rozpiska_sal.xlsx)

**Comment by mkdyderski** [comment]
@alicjaszabelska 
Jasne, taka może być?
![sale mapka](https://cloud.githubusercontent.com/assets/10108922/19033595/737818d0-895f-11e6-98be-ff51ce33165d.jpg)

**Comment by BERENZ** [comment]
@mkdyderski proponuje czarno-białą i bez satelity. Mógłbyś zrobić tez coś takiego dla 13 i 14?

**Comment by mkdyderski** [comment]
@BERENZ @alicjaszabelska  coś takiego?
Dla 13 i 14 rozumiem UEP (gmach główny) i przystanki tylko, czy coś jeszcze?
![sale mapka-bw](https://cloud.githubusercontent.com/assets/10108922/19034376/5ae966ee-8963-11e6-9294-e800e7bd0c23.jpg)

**Comment by BERENZ** [comment]
@mkdyderski tak, a dałoby radę opisy miejsc mieć w j. angielskim? Pytanie czy można zmienić to co Google wyrzuca?

**Comment by mkdyderski** [comment]
@BERENZ nie za bardzo - na mapach google opisy są w języku danego kraju. OSM też ma takie opisy. Może coś takiego - trochę hipsterskie, ale może się wpasuje w klimat?:)
![sale mapka-bw-toner](https://cloud.githubusercontent.com/assets/10108922/19034875/5b807e3c-8966-11e6-983b-9a6d2386ae4d.jpg)

**Comment by BERENZ** [comment]
@mkdyderski mi się podoba :)

**Comment by mkdyderski** [comment]
@BERENZ ok, to robię podobną dla UEP

**Comment by BERENZ** [comment]
@mkdyderski jak coś zamieść kod żeby szybko zmienić. :)

**Comment by mkdyderski** [comment]
![uep_mapka-bw-toner](https://cloud.githubusercontent.com/assets/10108922/19035323/33bea0e2-8969-11e6-952a-129e1492a542.jpg)

**Comment by mkdyderski** [comment]
Tutaj jest kod - [plik eRum misc.R](https://github.com/mkdyderski/Book-of-abstracts/blob/mkdyderski-mapka/eRum%20misc.R)
A [tutaj](https://github.com/mkdyderski/Book-of-abstracts/tree/mkdyderski-mapka/gis) pliki z warstwami punktowymi użyte do mapki,

**Comment by BERENZ** [comment]
@mkdyderski - proszę zmień z UEP na PUEB (od angielskiego skrótu). Najlepiej "PUEB - the venue". 

Dodaj jeszcze plac Mickiewicza jako "buses to the Welcome paRty".

**Comment by Nowosad** [comment]
Hej, w którym miejscu księgi chcecie, żeby te mapki były?

**Comment by BERENZ** [comment]
Proponuje na końcu 

Maciej Beręsewicz

**Comment by alicjaszabelska** [comment]
@mkdyderski proszę dodaj jeszcze stołówkę UP na mapie. Dzięki!

**Comment by Nowosad** [comment]
Aha, @mkdyderski - jak możesz to te dwie mapki podpisz u góry i połącz je w jeden plik graficzny - wtedy się poprostu w tej formie doda (na całą stronę) w księdze abstraktów.

**Comment by Nowosad** [comment]
Dodałem mapę z warsztatami do księgi. Jak coś się w niej zmieni - dajcie znać.

**Comment by mkdyderski** [comment]
@alicjaszabelska wrzucam mapkę z dodaną stołówką. Sorry za opóźnienie - jestem w terenie pod Bełchatowem i internet trzeba sobie przynosić wiaderkiem;)
![sale mapka-bw-toner](https://cloud.githubusercontent.com/assets/10108922/19124431/75a3307e-8b33-11e6-8fc9-5bd7b6aeaed8.jpg)

**Comment by mkdyderski** [comment]
@Nowosad 
dodaję łączoną
![laczona](https://cloud.githubusercontent.com/assets/10108922/19124679/7dc9ec2e-8b34-11e6-813d-e20a342536cf.jpg)

**Comment by Nowosad** [comment]
Done.
