### ISSUE TITLE
Dodanie nr sal na warsztaty

### ISSUE THREAD

**Issue by alicjaszabelska** [eRum2016/Book-of-abstracts#12]
@mkdyderski, @Nowosad czy moglibyście w księdze strzeszczeń dodać info na temat miejsca warsztatów? Tutaj jest rozpiska

[rozpiska_sal.xlsx](https://github.com/eRum2016/Book-of-abstracts/files/505697/rozpiska_sal.xlsx)

**Comment by Nowosad** [comment]
Jasne - zobacz tylko jak wygląda aktualna wersja książki i daj mi znać w którym miejscu to ma być.

**Comment by BERENZ** [comment]
@Nowosad dziś zaktualizowaliśmy plan. Najbardziej aktualna wersja jest na google drive (plik `Preliminary program`).

**Comment by Nowosad** [comment]
Pewnie w środę się tym zajmę - tj. upewnię się, że jest aktualna wersja programu w księdze. Wracając do wcześniejszego pytania - w którym miejscu chcecie mieć tą tabelę z info na temat miejsca warsztatów?

**Comment by BERENZ** [comment]
Proponuje po programie szczegółowym a przed abstraktami.

Maciej Beręsewicz

**Comment by Nowosad** [comment]
Done
