### ISSUE TITLE
Sekcja "places"

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#15]
Przydałaby się sekcja z adresami gdzie co dokładnie jest (warsztaty, konferencja) żeby mogli sobie googlać.

**Comment by BERENZ** [comment]
@Nowosad czy można usunąć tę linię poniżej tabeli z warsztatami, a tabelę zrobić na tę samą szerokość co mapy? Proponuję też dać kod QR to repo z warsztatami.

**Comment by Nowosad** [comment]
Done
