### ISSUE TITLE
Sekcja "social events"

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#18]
Tu dodam info co powinno się tutaj znaleźć.

**Comment by BERENZ** [comment]
We would like to kindly invite you to participate in the following social events:
1. Thursday, 13.10 at 20:00 — Welcome paRty (only for the conference participants, included in the conference fee):
- The Welcome paRty will be held on 13th of October and starts at 20:00 and ends at 2:00;
- The venue is the INEA Stadium, the stadium of Lech Poznań football club (Bułgarska 17 street);
- Buses will take conference participants to the Welcome paRty at 19:45 from Plac Mickiewicza (see maps);
- a poster session will be held during the welcome paRty;
- During the welcome paRty it will be possible to take a tour of the stadium for 10 PLN / person (not included in the fee, only Polish currency is accepted). The tour takes about 1 hour and a maximum of 40 persons can take aprt. During the tour you can see, among other things: 
  - the conference hall, 
  - the cloakroom for guest teams,
  - the pitch with reserve benches, 
  - the Lodge of Presidents,  
  - the Hall of Fame, 
  - the Press Tribune.
- We've arranged buses to take you from the Venue to the City Center that will depart according to the schedule below. If you would like to return earlier, you should consider taking tram 13 or 15 that leaves from the stop "Inea Stadion". 
  - 23:30
  - 00:00
  - 00:30
  - 01:00
  - 01:30
  - 02:00 
1. Friday, 15.10 at 19:00 — A closing get-together with the organisers over beer in the City Center (for all participants, facultative, not included in fees). We kindly invite you to "Piwna Stopa" Pub located in Szewska 7 street.
2. Saturday, 16.10 at 9:50 — A sightseeing tour in the center of Poznań (for all participants, facultative, not included in the conference fee). The total cost of the tour and lunch is 50 PLN / 15 EUR, and this should be paid in cash on arrival during the registration. The program is the following:
- 09:50 – 12:50 Sightseeing tour, starting point at University of Economics (al. Niepodległości, 10);
- 13.00 – 14.30 Lunch at Chłopskie Jadło restaurant (ul. Fredry 12).

**Comment by BERENZ** [comment]
@adolfoalvarez please check if everything is clear. In the end I inform where is the welcome paRty.

**Comment by Nowosad** [comment]
Trochę przedytowałem tekst i dodałem do księgi abstraktów.
