### ISSUE TITLE
Wielu autorów

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#2]
Hej, zauważyłem, że w książce streszczeń są podani tylko główni autorzy. Trzeba dodać pozostałych autorów.

**Comment by Nowosad** [comment]
Nie rozumiem... Możesz podać jakiś szczegół?

**Comment by BERENZ** [comment]
Na przykład (z arkusza referaty)

cgmisc: enhanced genome-wide association analyses and visualization — Jagoda Jabłońska;2.Marcin Kierczak;3.Simon Forsberg   

Enterprise R Platform – the what, the why and the how  — Gergely Mark; Csongor Somogyi; David Kun

**Comment by Nowosad** [comment]
https://github.com/eRum2016/Book-of-abstracts/blob/master/boa.pdf - ale tutaj są Ci autorzy wymienieni...?

**Comment by BERENZ** [comment]
A rzeczywiście mój błąd. Przepraszam.

**Comment by Nowosad** [comment]
no problemo;)
