### ISSUE TITLE
Sekcja "Venues"

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#26]
List of venues:
1. 12th of September:
- Poznan University of Life Sciences, Wojska Polskiego 28 street;
- Statistical Office in Poznan, Wojska Polskiego 27/29 street;
- **Registration**: Collegium Maximum, ground floor (ul. Wojska Polskiego 28);
1. 13th - 14th of September — Poznan University of Economics and Business, Al. Niepodleglosci 10, 
- **Registration**: Main Building, ground floor (al. Niepodleglosci 10 street)
1. 13th of September — the INEA Stadium, Bułgarska 17 street.
2. 14th of September — "Piwna Stopa" Pub, Szewska 7 street.

**Comment by BERENZ** [comment]
@eRum2016/dziewczyny-up proszę sprawdzie. @adolfoalvarez is it clear enough?

**Comment by alicjaszabelska** [comment]
@eRum2016/dziewczyny-up 

Może przy rejestracji dodać dokładne miejsce 

Registration: Collegium Maximum, ground floor, entrance next to ul. Wojska Polskiego (ul. Wojska Polskiego 28);

Co myślicie?

**Comment by Nowosad** [comment]
Dodane w wersji Macieja, jak macie jakieś pomysły zmian to proszę o pull requesta.
