### ISSUE TITLE
Struktura

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#29]
Proponuję:
- [x] - "Welcome to eRum 2016" dać zaraz po "The Organising committee" 
- [x] - Spis treści dałbym zaraz po stronie tytułowej przed "The Organizing Committee"
- [x] - czy da się zachować nagłówki tabeli ze szczegółowym planem?
- [ ] - czy da sie jakąś cienką linią rozdzielić prezentacje w ramach sesji? 
- [ ] - wycentrowałbym kod QR

@mkdyderski jeszcze dołączy mapę okolic stadionu.

**Comment by Nowosad** [comment]
> czy da się zachować nagłówki tabeli ze szczegółowym planem?

Hm.. nie do końca wiem co masz na myśli. Możesz wyjaśnić?

> czy da sie jakąś cienką linią rozdzielić prezentacje w ramach sesji? 

Mówisz o tabeli ze szczegółowym planem?

> wycentrowałbym kod QR

Próbowałem ten kod w kilku miejscach - na środku nie wygląda lepiej...

> @mkdyderski jeszcze dołączy mapę okolic stadionu. 

Gdzie będzie jej miejsce?

**Comment by BERENZ** [comment]
@Nowosad 
1. Chodzi o to żeby nagłówek tabeli przechodził i był na każdej stronie, a nie tylko na początku
2. Tak, chodzi o tabelę ze szczegółowym planem
3. Ok, to niech QR zostanie tam gdzie jest.
4. Jako druga strona w sekcji "social events".

**Comment by Nowosad** [comment]
Okej, czekam na mapę. Jak będzie to postaram się nanieść też pozostałe rzeczy (jeżeli się nauczę jak to zrobić;))

**Comment by mkdyderski** [comment]
@BERENZ @Nowosad 
przesyłam mapkę - sorry za opóźnienie, w Hubach Ruszczyńskich internet jest kapryśny;)

![mapka-stadion](https://cloud.githubusercontent.com/assets/10108922/19166782/3267caaa-8c09-11e6-9d85-34f5b22cabc4.jpg)

**Comment by Nowosad** [comment]
Kolejny update zrobiony.

**Comment by BERENZ** [comment]
@Nowosad naprawdę świetna robota! Jestem pełen podziwu jak ogarnąłeś z @mkdyderski tę książkę streszczeń. :)

**Comment by Nowosad** [comment]
Dobra grupowa robota - w końcu oprócz @mkdyderski i mnie to jeszcze masa innych osób przy tym pomagała (okładka, wstęp, program, etc.)

Książka w druku (?) - zamykam issue.
