### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by adolfoalvarez** [eRum2016/Book-of-abstracts#33]
In the venues.tex file all dates refer to September instead of October. I guess now is too late to change or re print, but at least it can be corrected in the pdf version available here.

**Comment by BERENZ** [comment]
Too late….

**Comment by adolfoalvarez** [comment]
```
                                                                                  I know but can it be fixed for the online version?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Play network.                                                                                                                                                                                                                From: Maciej BeręsewiczSent: Sunday, 9 October 2016 6:49 PMTo: eRum2016/Book-of-abstractsReply To: eRum2016/Book-of-abstractsCc: Adolfo Álvarez; AuthorSubject: Re: [eRum2016/Book-of-abstracts] Typo found (#33)Too late….
```

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eRum2016/Book-of-abstracts","title":"eRum2016/Book-of-abstracts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/eRum2016/Book-of-abstracts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BERENZ in #33: Too late…."}],"action":{"name":"View Issue","url":"https://github.com/eRum2016/Book-of-abstracts/issues/33#issuecomment-252497619"}}}

**Comment by Nowosad** [comment]
Fixed.
