### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#5]
@Nowosad @mkdyderski właśnie działam nad abstraktem i zastanawiam się czy mogę dodać cytowania literatury? Jeżeli, tak to mogę zrobić to przez bibtex? Widziałem, że w niektórych abstraktach jest literatura ale w księdze nie ma (por. EnvCpt: An R package for changepoint identification in Environmental data).

**Comment by mkdyderski** [comment]
@BERENZ stwierdziliśmy z @Nowosad że ją usuniemy, ponieważ występowała tylko w części abstraktów, a w części była podana tylko jako spis kilku pozycji, bez odniesień do tekstu. W kilku były odniesienia do literatury, ale tak zmodyfikowaliśmy treść wystąpień, że bez straty można było się ich pozbyć. Także myślę, że lepiej będzie bez literatury.

**Comment by BERENZ** [comment]
@mkdyderski ok, mam nadzieję, że nikt nie będzie protestował. Proponuję żebyście jutro wieczorem przesłali do osób, które mają referaty mail z informację, że ich abstrakty znajdują się na github w tym repo i do 6 października (23:59) mogą wprowadzać zmiany/korekty. Wtedy zrobimy akcja kompilacja i idzie do druku.

**Comment by Nowosad** [comment]
@mkdyderski informację rozesłał - kilka zmian już zostało naniesionych.
