### ISSUE TITLE
Rabczenko

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#8]
Brakuje abstraktu Rabczenko (poster) - Mortality mapping using R. Jest w `eRum form (Responses)`.

**Comment by Nowosad** [comment]
@BERENZ daj mi znać jak wygląda ta kwestia, bo:
1. Przygotowywałem listę abstraktów automatycznie kilka tygodni temu i nie było tego abstraktu wtedy (chyba...)
2. Tego posteru też nie ma w programie konferencji...

**Comment by BERENZ** [comment]
@Nowosad własnie jest w  `eRum form (Responses)` ale nie ma w innych plikach...

**Comment by Nowosad** [comment]
Dodałem ten poster i do tabeli z pełnym programem i do księgi abstraktów.
